### ISSUE TITLE
the urls of dataset and pretrained models are invalid now!

### ISSUE THREAD

**Issue by bravesailor** [denis-sumin/neural-scattering-prediction#2]
thank you for you greate work! it's really cool!  
the urls of dataset and pretrained models are invalid now, would you please update them please!

**Comment by diiigle** [comment]
Thank you for the notification, I will investigate what happened to the website. We don't have personal access to the institutional infrastructure any more so this may take some time.

**Comment by denis-sumin** [comment]
Hi @bravesailor , sorry that we had to spend some time to fix the URLs to the models and datasets. Now they are finally fixed, and you can download them.
